---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: avarteqgmbh/pipeline-utils

inputs:
- name: boshrelease
- name: pipelines-utils

outputs:
- name: boshrelease

run:
  path: pipelines-utils/scripts/deploy-release.sh
  args: ["populate-database"]

params:
  RELEASE_PATH:
  BOSH_ENVIRONMENT:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_CA_CERT:
